### PR TITLE
modifications to user and user related entities

### PR DESCRIPTION
**Pull request by ghost**
finished editing the entities to conform to our data model

### CODE REVIEW

**Review by Markelfdez — APPROVED** [review]
everything good imo

**Review by NicoRodBilbao — CHANGES_REQUESTED** [review]
I think that a compound id is necessary for _SignInHistory.java_ since different users can eventually sign in at the same time.

**Comment by ghost** [comment]
ok, changing it right now

**Review by NicoRodBilbao — APPROVED** [review]
Looks good to me.

**Review by mlnnzr — APPROVED** [review]
I think it´s ok

**Pull request merged**
