### PR TITLE
Finished the first version of the entities Item, Model and Report. Ad…

### PR DESCRIPTION
**Pull request by NicoRodBilbao**
…ded the class diagram too(See Storio).

### CODE REVIEW

**Review by Markelfdez — APPROVED** [review]
Good changes

**Review by ghost — CHANGES_REQUESTED** [review]
please remove the .class files before we proceed

**Comment by NicoRodBilbao** [comment]
> please remove the .class files before we proceed

The .class files belong to the UML diagram and they are necessary for its functioning on JDeveloper. 
Sorry for the misunderstanding.

**Review by ghost — APPROVED** [review]
ok @mlnnzr merge after checking the changes

**Review by mlnnzr — APPROVED** [review]
all good

**Pull request merged**
