### PR TITLE
pushing

### PR DESCRIPTION
**Pull request by Markelfdez**

### CODE REVIEW

**Review by NicoRodBilbao — CHANGES_REQUESTED** [review]
AbstractFacade is being used on some methods, that is not the correct way.

**Review by ghost — APPROVED** [review]

**Review by NicoRodBilbao — CHANGES_REQUESTED** [review]
In this pull request, my code from the main branch is deleted, please don't do that.

**Review by NicoRodBilbao — APPROVED** [review]
Seems good.

**Review by mlnnzr — APPROVED** [review]
Ok

**Pull request merged**
