### PR TITLE
Pack rest ejb

### PR DESCRIPTION
**Pull request by mlnnzr**

### CODE REVIEW

**Review by Markelfdez — APPROVED** [review]
okey

**Review by NicoRodBilbao — DISMISSED** [review]
I would not, under any circumstances, change the _persistence.xml_ file for anything but the <persistence> property.

**Review by NicoRodBilbao — CHANGES_REQUESTED** [review]
_FindException_ comment has been changed and it makes no sense.

**Review by NicoRodBilbao — APPROVED** [review]
I hope this one merges well with all the code.

**Review by ghost — APPROVED** [review]
okidoki

**Pull request merged**
