### PR TITLE
Fix user imports

### PR DESCRIPTION
**Pull request by ghost**
fix imports and update hashcode & equals methods

### CODE REVIEW

**Review by Markelfdez — APPROVED** [review]
good imo

**Review by mlnnzr — APPROVED** [review]
ok

**Review by NicoRodBilbao — CHANGES_REQUESTED** [review]
1. The relation of _Booking_ with _User_ is nonexistent, it should be with _Client_ instead.
2. The annontations _@Table_ and _@Entity_ are incompatible with _@MappedSuperclass_.

**Comment by ghost** [comment]
fixed annotation errors, add getters and seters and corrected booking -- client/user relation

**Review by NicoRodBilbao — CHANGES_REQUESTED** [review]
_Admin_ class is missing the _@Entity_ annotation.

**Review by NicoRodBilbao — CHANGES_REQUESTED** [review]
The _HistoryId_ bean is missing a _toString()_ method.

**Review by NicoRodBilbao — APPROVED** [review]
Looks good to me.

**Pull request merged**
